<?php

namespace App\Filament\Resources\Trinity\Characters\Characters\Schemas;

use Filament\Forms\Components\TextInput;
use Filament\Forms\Components\Textarea;
use Filament\Schemas\Schema;

class CharacterForm
{
    public static function configure(Schema $schema): Schema
    {
        return $schema
            ->components([
                TextInput::make('account')
                    ->required()
                    ->numeric()
                    ->default(0),
                TextInput::make('name'),
                TextInput::make('race')
                    ->required()
                    ->numeric()
                    ->default(0),
                TextInput::make('class')
                    ->required()
                    ->numeric()
                    ->default(0),
                TextInput::make('gender')
                    ->required()
                    ->numeric()
                    ->default(0),
                TextInput::make('level')
                    ->required()
                    ->numeric()
                    ->default(0),
                TextInput::make('xp')
                    ->required()
                    ->numeric()
                    ->default(0),
                TextInput::make('money')
                    ->required()
                    ->numeric()
                    ->default(0)
                    ->prefix('$'),
                TextInput::make('skin')
                    ->required()
                    ->numeric()
                    ->default(0),
                TextInput::make('face')
                    ->required()
                    ->numeric()
                    ->default(0),
                TextInput::make('hairStyle')
                    ->required()
                    ->numeric()
                    ->default(0),
                TextInput::make('hairColor')
                    ->required()
                    ->numeric()
                    ->default(0),
                TextInput::make('facialStyle')
                    ->required()
                    ->numeric()
                    ->default(0),
                TextInput::make('bankSlots')
                    ->required()
                    ->numeric()
                    ->default(0),
                TextInput::make('restState')
                    ->required()
                    ->numeric()
                    ->default(0),
                TextInput::make('playerFlags')
                    ->required()
                    ->numeric()
                    ->default(0),
                TextInput::make('position_x')
                    ->required()
                    ->numeric()
                    ->default(0),
                TextInput::make('position_y')
                    ->required()
                    ->numeric()
                    ->default(0),
                TextInput::make('position_z')
                    ->required()
                    ->numeric()
                    ->default(0),
                TextInput::make('map')
                    ->required()
                    ->numeric()
                    ->default(0),
                TextInput::make('instance_id')
                    ->required()
                    ->numeric()
                    ->default(0),
                TextInput::make('instance_mode_mask')
                    ->required()
                    ->numeric()
                    ->default(0),
                TextInput::make('orientation')
                    ->required()
                    ->numeric()
                    ->default(0),
                Textarea::make('taximask')
                    ->required()
                    ->columnSpanFull(),
                TextInput::make('online')
                    ->required()
                    ->numeric()
                    ->default(0),
                TextInput::make('cinematic')
                    ->required()
                    ->numeric()
                    ->default(0),
                TextInput::make('totaltime')
                    ->required()
                    ->numeric()
                    ->default(0),
                TextInput::make('leveltime')
                    ->required()
                    ->numeric()
                    ->default(0),
                TextInput::make('logout_time')
                    ->required()
                    ->numeric()
                    ->default(0),
                TextInput::make('is_logout_resting')
                    ->required()
                    ->numeric()
                    ->default(0),
                TextInput::make('rest_bonus')
                    ->required()
                    ->numeric()
                    ->default(0),
                TextInput::make('resettalents_cost')
                    ->required()
                    ->numeric()
                    ->default(0),
                TextInput::make('resettalents_time')
                    ->required()
                    ->numeric()
                    ->default(0),
                TextInput::make('trans_x')
                    ->required()
                    ->numeric()
                    ->default(0),
                TextInput::make('trans_y')
                    ->required()
                    ->numeric()
                    ->default(0),
                TextInput::make('trans_z')
                    ->required()
                    ->numeric()
                    ->default(0),
                TextInput::make('trans_o')
                    ->required()
                    ->numeric()
                    ->default(0),
                TextInput::make('transguid')
                    ->required()
                    ->numeric()
                    ->default(0),
                TextInput::make('extra_flags')
                    ->required()
                    ->numeric()
                    ->default(0),
                TextInput::make('stable_slots')
                    ->required()
                    ->numeric()
                    ->default(0),
                TextInput::make('at_login')
                    ->required()
                    ->numeric()
                    ->default(0),
                TextInput::make('zone')
                    ->required()
                    ->numeric()
                    ->default(0),
                TextInput::make('death_expire_time')
                    ->required()
                    ->numeric()
                    ->default(0),
                Textarea::make('taxi_path')
                    ->columnSpanFull(),
                TextInput::make('arenaPoints')
                    ->required()
                    ->numeric()
                    ->default(0),
                TextInput::make('totalHonorPoints')
                    ->required()
                    ->numeric()
                    ->default(0),
                TextInput::make('todayHonorPoints')
                    ->required()
                    ->numeric()
                    ->default(0),
                TextInput::make('yesterdayHonorPoints')
                    ->required()
                    ->numeric()
                    ->default(0),
                TextInput::make('totalKills')
                    ->required()
                    ->numeric()
                    ->default(0),
                TextInput::make('todayKills')
                    ->required()
                    ->numeric()
                    ->default(0),
                TextInput::make('yesterdayKills')
                    ->required()
                    ->numeric()
                    ->default(0),
                TextInput::make('chosenTitle')
                    ->required()
                    ->numeric()
                    ->default(0),
                TextInput::make('knownCurrencies')
                    ->required()
                    ->numeric()
                    ->default(0),
                TextInput::make('watchedFaction')
                    ->required()
                    ->numeric()
                    ->default(0),
                TextInput::make('drunk')
                    ->required()
                    ->numeric()
                    ->default(0),
                TextInput::make('health')
                    ->required()
                    ->numeric()
                    ->default(0),
                TextInput::make('power1')
                    ->required()
                    ->numeric()
                    ->default(0),
                TextInput::make('power2')
                    ->required()
                    ->numeric()
                    ->default(0),
                TextInput::make('power3')
                    ->required()
                    ->numeric()
                    ->default(0),
                TextInput::make('power4')
                    ->required()
                    ->numeric()
                    ->default(0),
                TextInput::make('power5')
                    ->required()
                    ->numeric()
                    ->default(0),
                TextInput::make('power6')
                    ->required()
                    ->numeric()
                    ->default(0),
                TextInput::make('power7')
                    ->required()
                    ->numeric()
                    ->default(0),
                TextInput::make('latency')
                    ->required()
                    ->numeric()
                    ->default(0),
                TextInput::make('talentGroupsCount')
                    ->required()
                    ->numeric()
                    ->default(1),
                TextInput::make('activeTalentGroup')
                    ->required()
                    ->numeric()
                    ->default(0),
                Textarea::make('exploredZones')
                    ->columnSpanFull(),
                Textarea::make('equipmentCache')
                    ->columnSpanFull(),
                TextInput::make('ammoId')
                    ->required()
                    ->numeric()
                    ->default(0),
                Textarea::make('knownTitles')
                    ->columnSpanFull(),
                TextInput::make('actionBars')
                    ->required()
                    ->numeric()
                    ->default(0),
                TextInput::make('grantableLevels')
                    ->required()
                    ->numeric()
                    ->default(0),
                TextInput::make('deleteInfos_Account')
                    ->numeric(),
                TextInput::make('deleteInfos_Name'),
                TextInput::make('deleteDate')
                    ->numeric(),
            ]);
    }
}
