<?php

namespace App\Filament\Resources\Trinity\World\ItemTemplates\Schemas;

use Filament\Forms\Components\TextInput;
use Filament\Schemas\Schema;

class ItemTemplateForm
{
    public static function configure(Schema $schema): Schema
    {
        return $schema
            ->components([
                TextInput::make('class')
                    ->required()
                    ->numeric()
                    ->default(0),
                TextInput::make('subclass')
                    ->required()
                    ->numeric()
                    ->default(0),
                TextInput::make('SoundOverrideSubclass')
                    ->required()
                    ->numeric()
                    ->default(-1),
                TextInput::make('name')
                    ->required(),
                TextInput::make('displayid')
                    ->required()
                    ->numeric()
                    ->default(0),
                TextInput::make('Quality')
                    ->required()
                    ->numeric()
                    ->default(0),
                TextInput::make('Flags')
                    ->required()
                    ->numeric()
                    ->default(0),
                TextInput::make('FlagsExtra')
                    ->required()
                    ->numeric()
                    ->default(0),
                TextInput::make('BuyCount')
                    ->required()
                    ->numeric()
                    ->default(1),
                TextInput::make('BuyPrice')
                    ->required()
                    ->numeric()
                    ->default(0),
                TextInput::make('SellPrice')
                    ->required()
                    ->numeric()
                    ->default(0),
                TextInput::make('InventoryType')
                    ->required()
                    ->numeric()
                    ->default(0),
                TextInput::make('AllowableClass')
                    ->required()
                    ->numeric()
                    ->default(-1),
                TextInput::make('AllowableRace')
                    ->required()
                    ->numeric()
                    ->default(-1),
                TextInput::make('ItemLevel')
                    ->required()
                    ->numeric()
                    ->default(0),
                TextInput::make('RequiredLevel')
                    ->required()
                    ->numeric()
                    ->default(0),
                TextInput::make('RequiredSkill')
                    ->required()
                    ->numeric()
                    ->default(0),
                TextInput::make('RequiredSkillRank')
                    ->required()
                    ->numeric()
                    ->default(0),
                TextInput::make('requiredspell')
                    ->required()
                    ->numeric()
                    ->default(0),
                TextInput::make('requiredhonorrank')
                    ->required()
                    ->numeric()
                    ->default(0),
                TextInput::make('RequiredCityRank')
                    ->required()
                    ->numeric()
                    ->default(0),
                TextInput::make('RequiredReputationFaction')
                    ->required()
                    ->numeric()
                    ->default(0),
                TextInput::make('RequiredReputationRank')
                    ->required()
                    ->numeric()
                    ->default(0),
                TextInput::make('maxcount')
                    ->required()
                    ->numeric()
                    ->default(0),
                TextInput::make('stackable')
                    ->numeric()
                    ->default(1),
                TextInput::make('ContainerSlots')
                    ->required()
                    ->numeric()
                    ->default(0),
                TextInput::make('StatsCount')
                    ->required()
                    ->numeric()
                    ->default(0),
                TextInput::make('stat_type1')
                    ->required()
                    ->numeric()
                    ->default(0),
                TextInput::make('stat_value1')
                    ->required()
                    ->numeric()
                    ->default(0),
                TextInput::make('stat_type2')
                    ->required()
                    ->numeric()
                    ->default(0),
                TextInput::make('stat_value2')
                    ->required()
                    ->numeric()
                    ->default(0),
                TextInput::make('stat_type3')
                    ->required()
                    ->numeric()
                    ->default(0),
                TextInput::make('stat_value3')
                    ->required()
                    ->numeric()
                    ->default(0),
                TextInput::make('stat_type4')
                    ->required()
                    ->numeric()
                    ->default(0),
                TextInput::make('stat_value4')
                    ->required()
                    ->numeric()
                    ->default(0),
                TextInput::make('stat_type5')
                    ->required()
                    ->numeric()
                    ->default(0),
                TextInput::make('stat_value5')
                    ->required()
                    ->numeric()
                    ->default(0),
                TextInput::make('stat_type6')
                    ->required()
                    ->numeric()
                    ->default(0),
                TextInput::make('stat_value6')
                    ->required()
                    ->numeric()
                    ->default(0),
                TextInput::make('stat_type7')
                    ->required()
                    ->numeric()
                    ->default(0),
                TextInput::make('stat_value7')
                    ->required()
                    ->numeric()
                    ->default(0),
                TextInput::make('stat_type8')
                    ->required()
                    ->numeric()
                    ->default(0),
                TextInput::make('stat_value8')
                    ->required()
                    ->numeric()
                    ->default(0),
                TextInput::make('stat_type9')
                    ->required()
                    ->numeric()
                    ->default(0),
                TextInput::make('stat_value9')
                    ->required()
                    ->numeric()
                    ->default(0),
                TextInput::make('stat_type10')
                    ->required()
                    ->numeric()
                    ->default(0),
                TextInput::make('stat_value10')
                    ->required()
                    ->numeric()
                    ->default(0),
                TextInput::make('ScalingStatDistribution')
                    ->required()
                    ->numeric()
                    ->default(0),
                TextInput::make('ScalingStatValue')
                    ->required()
                    ->numeric()
                    ->default(0),
                TextInput::make('dmg_min1')
                    ->required()
                    ->numeric()
                    ->default(0),
                TextInput::make('dmg_max1')
                    ->required()
                    ->numeric()
                    ->default(0),
                TextInput::make('dmg_type1')
                    ->required()
                    ->numeric()
                    ->default(0),
                TextInput::make('dmg_min2')
                    ->required()
                    ->numeric()
                    ->default(0),
                TextInput::make('dmg_max2')
                    ->required()
                    ->numeric()
                    ->default(0),
                TextInput::make('dmg_type2')
                    ->required()
                    ->numeric()
                    ->default(0),
                TextInput::make('armor')
                    ->required()
                    ->numeric()
                    ->default(0),
                TextInput::make('holy_res')
                    ->required()
                    ->numeric()
                    ->default(0),
                TextInput::make('fire_res')
                    ->required()
                    ->numeric()
                    ->default(0),
                TextInput::make('nature_res')
                    ->required()
                    ->numeric()
                    ->default(0),
                TextInput::make('frost_res')
                    ->required()
                    ->numeric()
                    ->default(0),
                TextInput::make('shadow_res')
                    ->required()
                    ->numeric()
                    ->default(0),
                TextInput::make('arcane_res')
                    ->required()
                    ->numeric()
                    ->default(0),
                TextInput::make('delay')
                    ->required()
                    ->numeric()
                    ->default(1000),
                TextInput::make('ammo_type')
                    ->required()
                    ->numeric()
                    ->default(0),
                TextInput::make('RangedModRange')
                    ->required()
                    ->numeric()
                    ->default(0),
                TextInput::make('spellid_1')
                    ->required()
                    ->numeric()
                    ->default(0),
                TextInput::make('spelltrigger_1')
                    ->required()
                    ->numeric()
                    ->default(0),
                TextInput::make('spellcharges_1')
                    ->required()
                    ->numeric()
                    ->default(0),
                TextInput::make('spellppmRate_1')
                    ->required()
                    ->numeric()
                    ->default(0),
                TextInput::make('spellcooldown_1')
                    ->required()
                    ->numeric()
                    ->default(-1),
                TextInput::make('spellcategory_1')
                    ->required()
                    ->numeric()
                    ->default(0),
                TextInput::make('spellcategorycooldown_1')
                    ->required()
                    ->numeric()
                    ->default(-1),
                TextInput::make('spellid_2')
                    ->required()
                    ->numeric()
                    ->default(0),
                TextInput::make('spelltrigger_2')
                    ->required()
                    ->numeric()
                    ->default(0),
                TextInput::make('spellcharges_2')
                    ->required()
                    ->numeric()
                    ->default(0),
                TextInput::make('spellppmRate_2')
                    ->required()
                    ->numeric()
                    ->default(0),
                TextInput::make('spellcooldown_2')
                    ->required()
                    ->numeric()
                    ->default(-1),
                TextInput::make('spellcategory_2')
                    ->required()
                    ->numeric()
                    ->default(0),
                TextInput::make('spellcategorycooldown_2')
                    ->required()
                    ->numeric()
                    ->default(-1),
                TextInput::make('spellid_3')
                    ->required()
                    ->numeric()
                    ->default(0),
                TextInput::make('spelltrigger_3')
                    ->required()
                    ->numeric()
                    ->default(0),
                TextInput::make('spellcharges_3')
                    ->required()
                    ->numeric()
                    ->default(0),
                TextInput::make('spellppmRate_3')
                    ->required()
                    ->numeric()
                    ->default(0),
                TextInput::make('spellcooldown_3')
                    ->required()
                    ->numeric()
                    ->default(-1),
                TextInput::make('spellcategory_3')
                    ->required()
                    ->numeric()
                    ->default(0),
                TextInput::make('spellcategorycooldown_3')
                    ->required()
                    ->numeric()
                    ->default(-1),
                TextInput::make('spellid_4')
                    ->required()
                    ->numeric()
                    ->default(0),
                TextInput::make('spelltrigger_4')
                    ->required()
                    ->numeric()
                    ->default(0),
                TextInput::make('spellcharges_4')
                    ->required()
                    ->numeric()
                    ->default(0),
                TextInput::make('spellppmRate_4')
                    ->required()
                    ->numeric()
                    ->default(0),
                TextInput::make('spellcooldown_4')
                    ->required()
                    ->numeric()
                    ->default(-1),
                TextInput::make('spellcategory_4')
                    ->required()
                    ->numeric()
                    ->default(0),
                TextInput::make('spellcategorycooldown_4')
                    ->required()
                    ->numeric()
                    ->default(-1),
                TextInput::make('spellid_5')
                    ->required()
                    ->numeric()
                    ->default(0),
                TextInput::make('spelltrigger_5')
                    ->required()
                    ->numeric()
                    ->default(0),
                TextInput::make('spellcharges_5')
                    ->required()
                    ->numeric()
                    ->default(0),
                TextInput::make('spellppmRate_5')
                    ->required()
                    ->numeric()
                    ->default(0),
                TextInput::make('spellcooldown_5')
                    ->required()
                    ->numeric()
                    ->default(-1),
                TextInput::make('spellcategory_5')
                    ->required()
                    ->numeric()
                    ->default(0),
                TextInput::make('spellcategorycooldown_5')
                    ->required()
                    ->numeric()
                    ->default(-1),
                TextInput::make('bonding')
                    ->required()
                    ->numeric()
                    ->default(0),
                TextInput::make('description')
                    ->required(),
                TextInput::make('PageText')
                    ->required()
                    ->numeric()
                    ->default(0),
                TextInput::make('LanguageID')
                    ->required()
                    ->numeric()
                    ->default(0),
                TextInput::make('PageMaterial')
                    ->required()
                    ->numeric()
                    ->default(0),
                TextInput::make('startquest')
                    ->required()
                    ->numeric()
                    ->default(0),
                TextInput::make('lockid')
                    ->required()
                    ->numeric()
                    ->default(0),
                TextInput::make('Material')
                    ->required()
                    ->numeric()
                    ->default(0),
                TextInput::make('sheath')
                    ->required()
                    ->numeric()
                    ->default(0),
                TextInput::make('RandomProperty')
                    ->required()
                    ->numeric()
                    ->default(0),
                TextInput::make('RandomSuffix')
                    ->required()
                    ->numeric()
                    ->default(0),
                TextInput::make('block')
                    ->required()
                    ->numeric()
                    ->default(0),
                TextInput::make('itemset')
                    ->required()
                    ->numeric()
                    ->default(0),
                TextInput::make('MaxDurability')
                    ->required()
                    ->numeric()
                    ->default(0),
                TextInput::make('area')
                    ->required()
                    ->numeric()
                    ->default(0),
                TextInput::make('Map')
                    ->required()
                    ->numeric()
                    ->default(0),
                TextInput::make('BagFamily')
                    ->required()
                    ->numeric()
                    ->default(0),
                TextInput::make('TotemCategory')
                    ->required()
                    ->numeric()
                    ->default(0),
                TextInput::make('socketColor_1')
                    ->required()
                    ->numeric()
                    ->default(0),
                TextInput::make('socketContent_1')
                    ->required()
                    ->numeric()
                    ->default(0),
                TextInput::make('socketColor_2')
                    ->required()
                    ->numeric()
                    ->default(0),
                TextInput::make('socketContent_2')
                    ->required()
                    ->numeric()
                    ->default(0),
                TextInput::make('socketColor_3')
                    ->required()
                    ->numeric()
                    ->default(0),
                TextInput::make('socketContent_3')
                    ->required()
                    ->numeric()
                    ->default(0),
                TextInput::make('socketBonus')
                    ->required()
                    ->numeric()
                    ->default(0),
                TextInput::make('GemProperties')
                    ->required()
                    ->numeric()
                    ->default(0),
                TextInput::make('RequiredDisenchantSkill')
                    ->required()
                    ->numeric()
                    ->default(-1),
                TextInput::make('ArmorDamageModifier')
                    ->required()
                    ->numeric()
                    ->default(0),
                TextInput::make('duration')
                    ->required()
                    ->numeric()
                    ->default(0),
                TextInput::make('ItemLimitCategory')
                    ->required()
                    ->numeric()
                    ->default(0),
                TextInput::make('HolidayId')
                    ->required()
                    ->numeric()
                    ->default(0),
                TextInput::make('ScriptName')
                    ->required(),
                TextInput::make('DisenchantID')
                    ->required()
                    ->numeric()
                    ->default(0),
                TextInput::make('FoodType')
                    ->required()
                    ->numeric()
                    ->default(0),
                TextInput::make('minMoneyLoot')
                    ->required()
                    ->numeric()
                    ->default(0),
                TextInput::make('maxMoneyLoot')
                    ->required()
                    ->numeric()
                    ->default(0),
                TextInput::make('flagsCustom')
                    ->required()
                    ->numeric()
                    ->default(0),
                TextInput::make('VerifiedBuild')
                    ->numeric(),
            ]);
    }
}
